// area manager event types

enum _AreaManagerEventType
{
  AREAEVENT_CALL_POLICE;
  AREAEVENT_ALERT_POLICE;
  AREAEVENT_ARRIVE_POLICE;
  AREAEVENT_CALL_POLICE_BACKUP;
  AREAEVENT_ARRIVE_POLICE_BACKUP;

  AREAEVENT_OBJECT_DECAY;
}
