// area manager event types

enum _AreaManagerEventType
{
  AREAEVENT_CALL_LAW;
  AREAEVENT_ALERT_LAW;
  AREAEVENT_ARRIVE_LAW;
  AREAEVENT_CALL_BACKUP;
  AREAEVENT_ARRIVE_BACKUP;

  AREAEVENT_OBJECT_DECAY;
}
