// player goals

enum _Goal
{
  GOAL_INVADE_HOST;
  GOAL_INVADE_HUMAN;
  GOAL_EVOLVE_PROBE;
  GOAL_EVOLVE_ORGAN;
  GOAL_PROBE_BRAIN;
  GOAL_LEARN_ITEMS;
  GOAL_PROBE_BRAIN_ADVANCED;
  GOAL_LEARN_SKILLS;
  GOAL_LEARN_SOCIETY;
}
