// player goals

enum _Goal
{
  GOAL_INVADE_HOST;
  GOAL_INVADE_HUMAN;
  GOAL_EVOLVE_PROBE;
  GOAL_EVOLVE_ORGAN;
  GOAL_GROW_ORGAN;
  GOAL_EVOLVE_MICROHABITAT;
  GOAL_CREATE_HABITAT;
  GOAL_PROBE_BRAIN;
  GOAL_LEARN_ITEMS;
  GOAL_PROBE_BRAIN_ADVANCED;
  GOAL_LEARN_SKILLS;
  GOAL_LEARN_SOCIETY;
  GOAL_TRAVEL_EVENT;
  GOAL_LEARN_CLUE;
  GOAL_LEARN_NPC;
  GOAL_USE_COMPUTER;

  // scenario: alien crash landing
  SCENARIO_ALIEN_FIND_SHIP;
  SCENARIO_ALIEN_SAVE_ALIEN;
  SCENARIO_ALIEN_ENTER_SHIP;
  SCENARIO_ALIEN_MISSION_ABDUCTION;
  SCENARIO_ALIEN_MISSION_ABDUCTION_GO_HABITAT;
  SCENARIO_ALIEN_MISSION_INFILTRATION;
  SCENARIO_ALIEN_MISSION_RESEARCH;
}
