// AI effect types

enum abstract _AIEffectType(String) to String from String
{
  var EFFECT_PARALYSIS = 'EFFECT_PARALYSIS';
  var EFFECT_SLIME = 'EFFECT_SLIME';
  var EFFECT_PANIC = 'EFFECT_PANIC';
  var EFFECT_CANNOT_TEAR_AWAY = 'EFFECT_CANNOT_TEAR_AWAY';
  var EFFECT_CRYING = 'EFFECT_CRYING';
  var EFFECT_BERSERK = 'EFFECT_BERSERK';
  var EFFECT_SMASH = 'EFFECT_SMASH';
  var EFFECT_BLEEDING = 'EFFECT_BLEEDING';
  var EFFECT_BLACK_NOISE = 'EFFECT_BLACK_NOISE';
  var EFFECT_WHITE_POWDER = 'EFFECT_WHITE_POWDER';
  var EFFECT_WITHDRAWAL = 'EFFECT_WITHDRAWAL';
  var EFFECT_DRUNK = 'EFFECT_DRUNK';
}
