// AI effect types

enum _AIEffectType
{
  EFFECT_PARALYSIS;
  EFFECT_SLIME;
  EFFECT_PANIC;
  EFFECT_CANNOT_TEAR_AWAY;
  EFFECT_CRYING;
  EFFECT_BERSERK;
  EFFECT_SMASH;
  EFFECT_BLEEDING;
  EFFECT_WHITE_POWDER;
  EFFECT_WITHDRAWAL;
  EFFECT_DRUNK;
}
