// AI states
enum abstract _AIState(String) to String from String
{
  var AI_STATE_IDLE = 'AI_STATE_IDLE';
  var AI_STATE_ALERT = 'AI_STATE_ALERT';
  var AI_STATE_SEARCH_LAST_SEEN = 'AI_STATE_SEARCH_LAST_SEEN';
  var AI_STATE_SEARCH_AREA = 'AI_STATE_SEARCH_AREA';
  var AI_STATE_HOST = 'AI_STATE_HOST';
  var AI_STATE_DEAD = 'AI_STATE_DEAD';
  var AI_STATE_POST_DETACH = 'AI_STATE_POST_DETACH';
  var AI_STATE_PRESERVED = 'AI_STATE_PRESERVED';
  var AI_STATE_MOVE_TARGET = 'AI_STATE_MOVE_TARGET';
  var AI_STATE_POST_DETACH_MEMORIES = 'AI_STATE_POST_DETACH_MEMORIES';
  var AI_STATE_INVESTIGATE = 'AI_STATE_INVESTIGATE';
}
