// AI states
enum _AIState
{
  AI_STATE_IDLE;
  AI_STATE_ALERT;
  AI_STATE_HOST;
  AI_STATE_DEAD;
  AI_STATE_POST_DETACH;
  AI_STATE_PRESERVED;
  AI_STATE_MOVE_TARGET;
  AI_STATE_POST_DETACH_MEMORIES;
  AI_STATE_INVESTIGATE;
}
