// AI trait types

enum abstract _AITraitType(String) to String from String
{
  var TRAIT_DRUG_ADDICT = 'TRAIT_DRUG_ADDICT';
  var TRAIT_ALCOHOLIC = 'TRAIT_ALCOHOLIC';
  var TRAIT_ASSIMILATED = 'TRAIT_ASSIMILATED';
  var TRAIT_BRUISER = 'TRAIT_BRUISER';
  var TRAIT_KNIFE_EXPERT = 'TRAIT_KNIFE_EXPERT';
  var TRAIT_BATON_EXPERT = 'TRAIT_BATON_EXPERT';
  var TRAIT_BATTER = 'TRAIT_BATTER';
  var TRAIT_GUERRERO = 'TRAIT_GUERRERO';
  var TRAIT_KENDOKA = 'TRAIT_KENDOKA';
  var TRAIT_PISTOL_MARKSMAN = 'TRAIT_PISTOL_MARKSMAN';
  var TRAIT_RIFLE_MARKSMAN = 'TRAIT_RIFLE_MARKSMAN';
  var TRAIT_BREACHER = 'TRAIT_BREACHER';
  var TRAIT_HACKER = 'TRAIT_HACKER';
  var TRAIT_COUNSELOR = 'TRAIT_COUNSELOR';
  var TRAIT_NEGOTIATOR = 'TRAIT_NEGOTIATOR';
  var TRAIT_CONSULTANT = 'TRAIT_CONSULTANT';
  var TRAIT_HABITUAL_LIAR = 'TRAIT_HABITUAL_LIAR';
  var TRAIT_DUMB = 'TRAIT_DUMB';
  var TRAIT_ILLITERATE = 'TRAIT_ILLITERATE';
  var TRAIT_GENIUS = 'TRAIT_GENIUS';
  var TRAIT_WEAK_WILLED = 'TRAIT_WEAK_WILLED';
  var TRAIT_STRONG_WILLED = 'TRAIT_STRONG_WILLED';
  var TRAIT_ANOREXIC = 'TRAIT_ANOREXIC';
  var TRAIT_WEAK = 'TRAIT_WEAK';
  var TRAIT_OBESE = 'TRAIT_OBESE';
  var TRAIT_HEAVILY_OBESE = 'TRAIT_HEAVILY_OBESE';
  var TRAIT_MUSCULAR = 'TRAIT_MUSCULAR';
  var TRAIT_HERCULEAN = 'TRAIT_HERCULEAN';
  var TRAIT_DEVOUT_BRUTE = 'TRAIT_DEVOUT_BRUTE';
  var TRAIT_PENITENT_BASTION = 'TRAIT_PENITENT_BASTION';
  var TRAIT_VEILED_SCHOLAR = 'TRAIT_VEILED_SCHOLAR';
  var TRAIT_HUSHED_SEER = 'TRAIT_HUSHED_SEER';
  var TRAIT_TITHE_HUSTLER = 'TRAIT_TITHE_HUSTLER';
  var TRAIT_VORACIOUS_ACCOUNTS = 'TRAIT_VORACIOUS_ACCOUNTS';
  var TRAIT_RITUAL_ENFORCER = 'TRAIT_RITUAL_ENFORCER';
  var TRAIT_INFIRM_WHISPERER = 'TRAIT_INFIRM_WHISPERER';
  var TRAIT_MASKED_LIAR = 'TRAIT_MASKED_LIAR';
  var TRAIT_VIGOROUS_FLAGELLANT = 'TRAIT_VIGOROUS_FLAGELLANT';
}
