// AI trait types

enum _AITraitType
{
  TRAIT_DRUG_ADDICT;
  TRAIT_ALCOHOLIC;
  TRAIT_ASSIMILATED;
  TRAIT_BRUISER;
  TRAIT_KNIFE_EXPERT;
  TRAIT_BATON_EXPERT;
  TRAIT_BATTER;
  TRAIT_GUERRERO;
  TRAIT_KENDOKA;
  TRAIT_PISTOL_MARKSMAN;
  TRAIT_RIFLE_MARKSMAN;
  TRAIT_BREACHER;
  TRAIT_HACKER;
  TRAIT_COUNSELOR;
  TRAIT_NEGOTIATOR;
  TRAIT_CONSULTANT;
  TRAIT_HABITUAL_LIAR;
  TRAIT_DUMB;
  TRAIT_GENIUS;
  TRAIT_WEAK_WILLED;
  TRAIT_STRONG_WILLED;
  TRAIT_ANOREXIC;
  TRAIT_WEAK;
  TRAIT_OBESE;
  TRAIT_HEAVILY_OBESE;
  TRAIT_MUSCULAR;
  TRAIT_HERCULEAN;
}
