// AI trait types

enum _AITraitType
{
  TRAIT_DRUG_ADDICT;
  TRAIT_ASSIMILATED;
  TRAIT_BRUISER;
  TRAIT_KNIFE_EXPERT;
  TRAIT_BATON_EXPERT;
  TRAIT_BATTER;
  TRAIT_GUERRERO;
  TRAIT_KENDOKA;
  TRAIT_PISTOL_MARKSMAN;
  TRAIT_RIFLE_MARKSMAN;
  TRAIT_BREACHER;
  TRAIT_HACKER;
  TRAIT_COUNSELOR;
  TRAIT_NEGOTIATOR;
  TRAIT_CONSULTANT;
  TRAIT_HABITUAL_LIAR;
}
