// area types

enum abstract _AreaType(String) to String from String
{
  var AREA_GROUND = 'AREA_GROUND';
  var AREA_CITY_LOW = 'AREA_CITY_LOW';
  var AREA_CITY_MEDIUM = 'AREA_CITY_MEDIUM';
  var AREA_CITY_HIGH = 'AREA_CITY_HIGH';
  var AREA_MILITARY_BASE = 'AREA_MILITARY_BASE';
  var AREA_FACILITY = 'AREA_FACILITY';
  var AREA_SEWERS = 'AREA_SEWERS';
  var AREA_UNDERGROUND_LAB = 'AREA_UNDERGROUND_LAB';
  var AREA_HABITAT = 'AREA_HABITAT';
  var AREA_CORP = 'AREA_CORP';
}
