// area manager event types

enum abstract _AreaManagerEventType(String) to String from String
{
  var AREAEVENT_CALL_LAW = 'AREAEVENT_CALL_LAW';
  var AREAEVENT_ALERT_LAW = 'AREAEVENT_ALERT_LAW';
  var AREAEVENT_ARRIVE_LAW = 'AREAEVENT_ARRIVE_LAW';
  var AREAEVENT_CALL_BACKUP = 'AREAEVENT_CALL_BACKUP';
  var AREAEVENT_ARRIVE_BACKUP = 'AREAEVENT_ARRIVE_BACKUP';
  var AREAEVENT_CALL_TEAM_BACKUP = 'AREAEVENT_CALL_TEAM_BACKUP';
  var AREAEVENT_ARRIVE_TEAM_BACKUP = 'AREAEVENT_ARRIVE_TEAM_BACKUP';

  var AREAEVENT_OBJECT_DECAY = 'AREAEVENT_OBJECT_DECAY';
  var AREAEVENT_ARRIVE_CULTIST = 'AREAEVENT_ARRIVE_CULTIST';
}
