// cult effect types

enum _CultEffectType
{
  CULT_EFFECT_NOTRADE;
  CULT_EFFECT_INCREASE_POWER;
  CULT_EFFECT_DECREASE_POWER;
  CULT_EFFECT_INCREASE_INCOME;
  CULT_EFFECT_DECREASE_INCOME;
  CULT_EFFECT_GAIN_RESOURCE;
  CULT_EFFECT_LOSE_RESOURCE;
  CULT_EFFECT_INCREASE_TRADE_COST;
  CULT_EFFECT_DECREASE_TRADE_COST;
  CULT_EFFECT_ORDEAL_ACTIONS;
  CULT_EFFECT_DIFFICULT_HELP;
  CULT_EFFECT_BLOCK_COMMUNAL;
}
