// cult effect types

enum abstract _CultEffectType(String) to String from String
{
  var CULT_EFFECT_NOTRADE = 'CULT_EFFECT_NOTRADE';
  var CULT_EFFECT_INCREASE_POWER = 'CULT_EFFECT_INCREASE_POWER';
  var CULT_EFFECT_DECREASE_POWER = 'CULT_EFFECT_DECREASE_POWER';
  var CULT_EFFECT_INCREASE_INCOME = 'CULT_EFFECT_INCREASE_INCOME';
  var CULT_EFFECT_DECREASE_INCOME = 'CULT_EFFECT_DECREASE_INCOME';
  var CULT_EFFECT_GAIN_RESOURCE = 'CULT_EFFECT_GAIN_RESOURCE';
  var CULT_EFFECT_LOSE_RESOURCE = 'CULT_EFFECT_LOSE_RESOURCE';
  var CULT_EFFECT_INCREASE_TRADE_COST = 'CULT_EFFECT_INCREASE_TRADE_COST';
  var CULT_EFFECT_DECREASE_TRADE_COST = 'CULT_EFFECT_DECREASE_TRADE_COST';
  var CULT_EFFECT_ORDEAL_ACTIONS = 'CULT_EFFECT_ORDEAL_ACTIONS';
  var CULT_EFFECT_DIFFICULT_HELP = 'CULT_EFFECT_DIFFICULT_HELP';
  var CULT_EFFECT_BLOCK_COMMUNAL = 'CULT_EFFECT_BLOCK_COMMUNAL';
  var CULT_EFFECT_BLOCK_CULTIST = 'CULT_EFFECT_BLOCK_CULTIST';
}
