// player goals
enum abstract _Goal(String) to String from String
{
  var GOAL_TUTORIAL_ALERT = 'GOAL_TUTORIAL_ALERT';
  var GOAL_TUTORIAL_BODY = 'GOAL_TUTORIAL_BODY';
  var GOAL_TUTORIAL_BODY_SEWERS = 'GOAL_TUTORIAL_BODY_SEWERS';
  var GOAL_TUTORIAL_ENERGY = 'GOAL_TUTORIAL_ENERGY';
  var GOAL_TUTORIAL_AREA_ALERT = 'GOAL_TUTORIAL_AREA_ALERT';
  var GOAL_TUTORIAL_COMMS = 'GOAL_TUTORIAL_COMMS';
  var GOAL_TUTORIAL_DEGRADE = 'GOAL_TUTORIAL_DEGRADE';
  var GOAL_TUTORIAL_AFFINITY = 'GOAL_TUTORIAL_AFFINITY';
  var GOAL_TUTORIAL_MAX_AFFINITY = 'GOAL_TUTORIAL_MAX_AFFINITY';
  var GOAL_TUTORIAL_CONSENT = 'GOAL_TUTORIAL_CONSENT';

  var GOAL_INVADE_HOST = 'GOAL_INVADE_HOST';
  var GOAL_INVADE_HUMAN = 'GOAL_INVADE_HUMAN';
  var GOAL_EVOLVE_PROBE = 'GOAL_EVOLVE_PROBE';
  var GOAL_EVOLVE_ORGAN = 'GOAL_EVOLVE_ORGAN';
  var GOAL_GROW_ORGAN = 'GOAL_GROW_ORGAN';

  var GOAL_EVOLVE_CAMO = 'GOAL_EVOLVE_CAMO';
  var GOAL_GROW_CAMO = 'GOAL_GROW_CAMO';

  var GOAL_EVOLVE_DOPAMINE = 'GOAL_EVOLVE_DOPAMINE';
  var GOAL_LEARN_PRESERVATOR = 'GOAL_LEARN_PRESERVATOR';

  var GOAL_EVOLVE_MICROHABITAT = 'GOAL_EVOLVE_MICROHABITAT';
  var GOAL_CREATE_HABITAT = 'GOAL_CREATE_HABITAT';
  var GOAL_PUT_BIOMINERAL = 'GOAL_PUT_BIOMINERAL';
  var GOAL_PUT_ASSIMILATION = 'GOAL_PUT_ASSIMILATION';
  var GOAL_PUT_WATCHER = 'GOAL_PUT_WATCHER';

  var GOAL_PROBE_BRAIN = 'GOAL_PROBE_BRAIN';
  var GOAL_LEARN_ITEMS = 'GOAL_LEARN_ITEMS';
  var GOAL_PROBE_BRAIN_ADVANCED = 'GOAL_PROBE_BRAIN_ADVANCED';
  var GOAL_LEARN_SKILLS = 'GOAL_LEARN_SKILLS';
  var GOAL_LEARN_SOCIETY = 'GOAL_LEARN_SOCIETY';
  var GOAL_ENTER_SEWERS = 'GOAL_ENTER_SEWERS';
  var GOAL_TRAVEL_EVENT = 'GOAL_TRAVEL_EVENT';
  var GOAL_LEARN_CLUE = 'GOAL_LEARN_CLUE';
  var GOAL_LEARN_NPC = 'GOAL_LEARN_NPC';
  var GOAL_USE_COMPUTER = 'GOAL_USE_COMPUTER';
  var GOAL_PROGRESS_TIMELINE = 'GOAL_PROGRESS_TIMELINE';
  var GOAL_LEARN_FALSE_MEMORIES = 'GOAL_LEARN_FALSE_MEMORIES';
  var GOAL_LEARN_ENGRAM = 'GOAL_LEARN_ENGRAM';

  // scenario: alien crash landing
  var SCENARIO_ALIEN_FIND_SHIP = 'SCENARIO_ALIEN_FIND_SHIP';
  var SCENARIO_ALIEN_SAVE_ALIEN = 'SCENARIO_ALIEN_SAVE_ALIEN';
  var SCENARIO_ALIEN_STEAL_SHIP = 'SCENARIO_ALIEN_STEAL_SHIP';
  var SCENARIO_ALIEN_ENTER_SHIP = 'SCENARIO_ALIEN_ENTER_SHIP';
  var SCENARIO_ALIEN_MISSION_ABDUCTION = 'SCENARIO_ALIEN_MISSION_ABDUCTION';
  var SCENARIO_ALIEN_MISSION_ABDUCTION_GO_SPACESHIP = 'SCENARIO_ALIEN_MISSION_ABDUCTION_GO_SPACESHIP';
  var SCENARIO_ALIEN_MISSION_FAILURE_GO_SPACESHIP = 'SCENARIO_ALIEN_MISSION_FAILURE_GO_SPACESHIP';
  var SCENARIO_ALIEN_MISSION_INFILTRATION = 'SCENARIO_ALIEN_MISSION_INFILTRATION';
  var SCENARIO_ALIEN_MISSION_RESEARCH = 'SCENARIO_ALIEN_MISSION_RESEARCH';
  var SCENARIO_ALIEN_MISSION_LIQUIDATION = 'SCENARIO_ALIEN_MISSION_LIQUIDATION';
  var SCENARIO_ALIEN_MISSION_INTEL = 'SCENARIO_ALIEN_MISSION_INTEL';
  var SCENARIO_ALIEN_MISSION_SUCCESS_GO_SPACESHIP = 'SCENARIO_ALIEN_MISSION_SUCCESS_GO_SPACESHIP';
}
