// player goals

enum _Goal
{
  GOAL_TUTORIAL_ALERT;
  GOAL_TUTORIAL_BODY;
  GOAL_TUTORIAL_BODY_SEWERS;
  GOAL_TUTORIAL_ENERGY;
  GOAL_TUTORIAL_AREA_ALERT;
  GOAL_TUTORIAL_COMMS;
  GOAL_TUTORIAL_DEGRADE;

  GOAL_INVADE_HOST;
  GOAL_INVADE_HUMAN;
  GOAL_EVOLVE_PROBE;
  GOAL_EVOLVE_ORGAN;
  GOAL_GROW_ORGAN;

  GOAL_EVOLVE_CAMO;
  GOAL_GROW_CAMO;

  GOAL_EVOLVE_DOPAMINE;

  GOAL_EVOLVE_MICROHABITAT;
  GOAL_CREATE_HABITAT;
  GOAL_PUT_BIOMINERAL;
  GOAL_PUT_ASSIMILATION;
  GOAL_PUT_WATCHER;

  GOAL_PROBE_BRAIN;
  GOAL_LEARN_ITEMS;
  GOAL_PROBE_BRAIN_ADVANCED;
  GOAL_LEARN_SKILLS;
  GOAL_LEARN_SOCIETY;
  GOAL_ENTER_SEWERS;
  GOAL_TRAVEL_EVENT;
  GOAL_LEARN_CLUE;
  GOAL_LEARN_NPC;
  GOAL_USE_COMPUTER;
  GOAL_PROGRESS_TIMELINE;

  // scenario: alien crash landing
  SCENARIO_ALIEN_FIND_SHIP;
  SCENARIO_ALIEN_SAVE_ALIEN;
  SCENARIO_ALIEN_ENTER_SHIP;
  SCENARIO_ALIEN_MISSION_ABDUCTION;
  SCENARIO_ALIEN_MISSION_ABDUCTION_GO_SPACESHIP;
  SCENARIO_ALIEN_MISSION_FAILURE_GO_SPACESHIP;
  SCENARIO_ALIEN_MISSION_INFILTRATION;
  SCENARIO_ALIEN_MISSION_RESEARCH;
}
