enum _Improv
{
  IMP_HOST_RELEASE;
  IMP_DECAY_ACCEL;
  IMP_CAMO_LAYER; // special
  IMP_DOPAMINE; // special
  IMP_BRAIN_PROBE; // special
  IMP_PROT_COVER;
  IMP_MUSCLE;
  IMP_WOUND_REGEN;
  IMP_HEALTH;
  IMP_ENERGY;
  IMP_HARDEN_GRIP;
  IMP_ATTACH;
  IMP_REINFORCE;
  IMP_ACID_SPIT;
  IMP_SLIME_SPIT;
  IMP_PARALYSIS_SPIT;
  IMP_PANIC_GAS;
  IMP_PARALYSIS_GAS;
  IMP_MICROHABITAT; // special
  IMP_BIOMINERAL; // special
  IMP_ASSIMILATION; // special
  IMP_WATCHER; // special
  IMP_PRESERVATOR; // special
  IMP_OVUM; // special
}
