// player action types

enum _PlayerActionType
{
  ACTION_DEBUG;
  ACTION_AREA;
  ACTION_REGION;
  ACTION_OBJECT;
  ACTION_ORGAN;
  ACTION_EVOLUTION;
  ACTION_INVENTORY;
  ACTION_UI;
  ACTION_CHAT;
  ACTION_CONVERSE_MENU;
  ACTION_HOST;
  ACTION_CULT;
}
