// player action types

enum abstract _PlayerActionType(String) to String from String
{
  var ACTION_DEBUG = 'ACTION_DEBUG';
  var ACTION_AREA = 'ACTION_AREA';
  var ACTION_REGION = 'ACTION_REGION';
  var ACTION_OBJECT = 'ACTION_OBJECT';
  var ACTION_ORGAN = 'ACTION_ORGAN';
  var ACTION_EVOLUTION = 'ACTION_EVOLUTION';
  var ACTION_INVENTORY = 'ACTION_INVENTORY';
  var ACTION_UI = 'ACTION_UI';
  var ACTION_CHAT = 'ACTION_CHAT';
  var ACTION_CONVERSE_MENU = 'ACTION_CONVERSE_MENU';
  var ACTION_HOST = 'ACTION_HOST';
  var ACTION_CULT = 'ACTION_CULT';
}
