enum _Skill
{
  SKILL_ATTACK;
  SKILL_FISTS;
  SKILL_BATON;
  SKILL_CLUB;
  SKILL_KNIFE;
  SKILL_MACHETE;
  SKILL_KATANA;
  SKILL_PISTOL;
  SKILL_RIFLE;
  SKILL_SHOTGUN;
  SKILL_COMPUTER;

  KNOW_SMOKING; // removed
  KNOW_SHOPPING; // removed
  KNOW_SOCIETY;

  SKILL_PSYCHOLOGY;
  SKILL_DECEPTION;
  SKILL_COERCION;
  SKILL_COAXING;
}
