// log text colors

enum abstract _TextColor(String) to String from String
{
  var COLOR_DEFAULT = 'COLOR_DEFAULT';
  var COLOR_DEBUG = 'COLOR_DEBUG';
  var COLOR_ALERT = 'COLOR_ALERT';
  var COLOR_EVOLUTION = 'COLOR_EVOLUTION';
  var COLOR_ORGAN = 'COLOR_ORGAN';
  var COLOR_HINT = 'COLOR_HINT';
  var COLOR_TIMELINE = 'COLOR_TIMELINE';
  var COLOR_MESSAGE = 'COLOR_MESSAGE';
  var COLOR_GOAL = 'COLOR_GOAL';
  var COLOR_PEDIA = 'COLOR_PEDIA';
  var COLOR_SYMBIOSIS = 'COLOR_SYMBIOSIS';
  var COLOR_CULT = 'COLOR_CULT';
}
