// cult UI state enum
enum _UICultState
{
  STATE_ROOT;
  STATE_INITIATE;
  STATE_RECRUIT;
  STATE_ORDEAL;
  STATE_TRADE;
  STATE_SELECT_RESOURCE;
  STATE_TRADE_RESOURCE;
  STATE_UPGRADE;
  STATE_UPGRADE_TWO;
  STATE_CALL_MEMBER;
  STATE_BAZAAR;
  STATE_BAZAAR_MEMBER;
  STATE_BAZAAR_EQUIP;
}
