// cult UI state enum
enum abstract _UICultState(String) to String from String
{
  var STATE_ROOT = 'STATE_ROOT';
  var STATE_INITIATE = 'STATE_INITIATE';
  var STATE_RECRUIT = 'STATE_RECRUIT';
  var STATE_ORDEAL = 'STATE_ORDEAL';
  var STATE_TRADE = 'STATE_TRADE';
  var STATE_SELECT_RESOURCE = 'STATE_SELECT_RESOURCE';
  var STATE_TRADE_RESOURCE = 'STATE_TRADE_RESOURCE';
  var STATE_UPGRADE = 'STATE_UPGRADE';
  var STATE_UPGRADE_TWO = 'STATE_UPGRADE_TWO';
  var STATE_CALL_MEMBER = 'STATE_CALL_MEMBER';
  var STATE_BAZAAR = 'STATE_BAZAAR';
  var STATE_BAZAAR_MEMBER = 'STATE_BAZAAR_MEMBER';
  var STATE_BAZAAR_EQUIP = 'STATE_BAZAAR_EQUIP';
  var STATE_BAZAAR_TRAIN_MEMBER = 'STATE_BAZAAR_TRAIN_MEMBER';
  var STATE_BAZAAR_TRAIN_SKILL = 'STATE_BAZAAR_TRAIN_SKILL';
}
